package com.monitorcheck.monitor

import android.app.*
import android.content.Context
import android.content.Intent
import android.content.pm.ServiceInfo
import android.os.Build
import android.os.IBinder
import androidx.core.app.NotificationCompat
import com.monitorcheck.MainActivity
import com.monitorcheck.R
import com.monitorcheck.core.*
import com.monitorcheck.data.battery.BatteryHistoryStore
import com.monitorcheck.data.battery.BatteryRepository
import com.monitorcheck.hardware.cpu.CpuRepository
import com.monitorcheck.hardware.memory.MemoryRepository
import com.monitorcheck.hardware.thermal.ThermalCategory
import com.monitorcheck.hardware.thermal.ThermalRepository
import com.monitorcheck.hardware.thermal.ThermalZone
import com.monitorcheck.network.NetworkRepository
import com.monitorcheck.storage.StorageRepository
import com.monitorcheck.widget.MonitorWidgetProvider
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.first

class MonitoringService : Service() {
    private val scope=CoroutineScope(SupervisorJob()+Dispatchers.Default); private var job:Job?=null; private var paused=false; private var muted=false; private val lastAlerts=HashMap<String,Long>()
    private lateinit var settingsRepo:SettingsRepository; private lateinit var cpu:CpuRepository; private lateinit var memory:MemoryRepository; private lateinit var battery:BatteryRepository; private lateinit var network:NetworkRepository; private lateinit var thermal:ThermalRepository; private lateinit var storage:StorageRepository; private lateinit var batteryHistory:BatteryHistoryStore; private lateinit var history:MonitoringHistoryStore; private lateinit var alertStore:AlertEventStore
    override fun onCreate(){super.onCreate();settingsRepo=SettingsRepository(applicationContext);cpu=CpuRepository();memory=MemoryRepository(applicationContext);battery=BatteryRepository(applicationContext);network=NetworkRepository(applicationContext);thermal=ThermalRepository(applicationContext);storage=StorageRepository(applicationContext);batteryHistory=BatteryHistoryStore(applicationContext);history=MonitoringHistoryStore(applicationContext);alertStore=AlertEventStore(applicationContext);createChannels()}
    override fun onStartCommand(intent:Intent?,flags:Int,startId:Int):Int{when(intent?.action){ACTION_STOP->{stopSelf();return START_NOT_STICKY};ACTION_PAUSE->paused=true;ACTION_RESUME->paused=false;ACTION_TOGGLE_ALERTS->muted=!muted};startForegroundCompat(buildNotification("Starting monitoring…",null));if(job?.isActive!=true)job=scope.launch{loop()};return START_STICKY}
    private suspend fun loop(){var tick=0L;while(scope.isActive){val s=runCatching{settingsRepo.settings.first()}.getOrDefault(AppSettings());val interval=maxOf(5_000L,if(s.lowResourceMode)s.refreshIntervalMs*2 else s.refreshIntervalMs);if(paused){notificationManager().notify(NOTIFICATION_ID,buildNotification("Monitoring paused","Press Resume to continue sampling."));delay(1_000);continue};val c=runCatching{collect(s)}.getOrNull();if(c!=null){notificationManager().notify(NOTIFICATION_ID,buildNotification(c.title,c.detail));MonitorWidgetProvider.updateAll(applicationContext,c.widget);if(!muted)evaluate(s,c.sample)};tick++;if(tick%720==0L){runCatching{batteryHistory.prune()};runCatching{history.prune(s.historyRetentionDays)}};delay(interval)}}
    private data class Collected(val title:String,val detail:String?,val sample:MonitorSample,val widget:MonitorWidgetProvider.WidgetSnapshot)
    private suspend fun collect(s:AppSettings):Collected{
        val u=runCatching{cpu.sampleUsage()}.getOrNull();val mem=runCatching{memory.snapshot()}.getOrElse{Reading.error(it.message)};val bat=runCatching{battery.snapshot()}.getOrElse{Reading.error(it.message)};val net=runCatching{network.sampleThroughput()}.getOrNull();val zones: Reading<List<ThermalZone>> = if(s.lowResourceMode)Reading.unavailable("Skipped in Low Resource Mode") else runCatching{thermal.readZones()}.getOrElse{Reading.error(it.message)};val hot=zones.value?.maxByOrNull{it.celsius}?.let{Reading.available(it.celsius,zones.source)}?:Reading(zones.status,null,zones.note,zones.source);val cpuTemp=zones.value?.filter{it.category==ThermalCategory.CPU}?.maxByOrNull{it.celsius}?.let{Reading.available(it.celsius,it.path)}?:Reading(zones.status,null,zones.note,zones.source);val batTemp=bat.value?.temperatureCelsius?.let{Reading.available(it,"BatteryManager")}?:Reading.unavailable("Not reported")
        val parts=ArrayList<String>();val detail=StringBuilder();if(s.notifyCpu){val t=u?.totalPercent?.display{Fmt.percent(it,0)}?:"Unavailable";parts.add("CPU $t");if(s.notificationStyle==NotificationStyle.DETAILED)detail.append("CPU: $t\n")};if(s.notifyRam){parts.add("RAM ${mem.display{Fmt.percent(it.usedPercent,0)}}");if(s.notificationStyle==NotificationStyle.DETAILED)mem.value?.let{detail.append("RAM: ${Fmt.bytes(it.usedBytes)} / ${Fmt.bytes(it.totalBytes)}\n")}};if(s.notifyBattery){parts.add("BAT ${bat.display{"${it.levelPercent}%"}}");bat.value?.let{if(s.batteryHistoryEnabled)runCatching{batteryHistory.record(it)};if(s.notificationStyle==NotificationStyle.DETAILED)detail.append("Battery: ${it.levelPercent}% ${it.status}\n")}};if(s.notifyNetwork)parts.add(if(net?.elapsedMs?:0>0)"NET ↓${Fmt.bytesPerSecond(net!!.rxRateBps)}" else "NET unavailable");if(s.notifyTemperature)hot.value?.let{parts.add("TMP ${Fmt.temperature(it)}")};val title=parts.take(if(s.notificationStyle==NotificationStyle.MINIMAL)3 else 6).joinToString("  |  ").ifBlank{"Monitoring active"}
        val sample=MonitorSample(System.currentTimeMillis(),u,mem,bat,net,hot,batTemp,Reading.unsupported("Not sampled"),Reading.unsupported("Not sampled"),cpuTemp);history.record(HistoryPoint(sample.timestamp,u?.totalPercent?.value,mem.value?.usedPercent,bat.value?.levelPercent?.toDouble(),batTemp.value,hot.value,net?.rxRateBps,net?.txRateBps));val widget=MonitorWidgetProvider.WidgetSnapshot(u?.totalPercent?.value?.let{Fmt.percent(it,0)}?:"Unavailable",mem.value?.let{Fmt.percent(it.usedPercent,0)}?:"Unavailable",bat.value?.let{"${it.levelPercent}%"}?:"Unavailable",hot.value?.let{Fmt.temperature(it)}?:"Unavailable",net?.takeIf{it.elapsedMs>0}?.let{"↓${Fmt.bytesPerSecond(it.rxRateBps)} ↑${Fmt.bytesPerSecond(it.txRateBps)}"}?:"Unavailable",System.currentTimeMillis());return Collected(title,detail.toString().trim().ifBlank{null},sample,widget)
    }
    private fun evaluate(s:AppSettings,sample:MonitorSample){val now=System.currentTimeMillis();AlertEvaluator(storage).evaluate(s,sample).forEach{a->if(now-(lastAlerts[a.key]?:0L)>=s.alertCooldownMs){lastAlerts[a.key]=now;val e=AlertEvent(now,a.key,a.title,a.detail);runCatching{alertStore.add(e)};notificationManager().notify(ALERT_ID+a.key.hashCode(),alertNotification(e))}}}
    private fun alertNotification(e:AlertEvent):Notification=NotificationCompat.Builder(this,ALERT_CHANNEL_ID).setSmallIcon(R.drawable.ic_notification).setContentTitle(e.title).setContentText(e.detail).setStyle(NotificationCompat.BigTextStyle().bigText(e.detail)).setContentIntent(mainIntent(2,"alerts")).setAutoCancel(true).setPriority(NotificationCompat.PRIORITY_HIGH).build()
    private fun buildNotification(text:String,detail:String?):Notification{val b=NotificationCompat.Builder(this,CHANNEL_ID).setSmallIcon(R.drawable.ic_notification).setContentTitle(getString(R.string.monitoring_notification_title)).setContentText(text).setContentIntent(mainIntent(0,"dashboard")).setOngoing(true).setSilent(true).setShowWhen(false).setPriority(NotificationCompat.PRIORITY_LOW).setCategory(NotificationCompat.CATEGORY_SERVICE);b.addAction(0,if(paused)"Resume" else "Pause",serviceIntent(1,if(paused)ACTION_RESUME else ACTION_PAUSE));b.addAction(0,if(muted)"Enable alerts" else "Mute alerts",serviceIntent(3,ACTION_TOGGLE_ALERTS));b.addAction(0,"Stop",serviceIntent(4,ACTION_STOP));if(!detail.isNullOrBlank())b.setStyle(NotificationCompat.BigTextStyle().bigText(detail));return b.build()}
    private fun mainIntent(code:Int,route:String)=PendingIntent.getActivity(this,code,Intent(this,MainActivity::class.java).apply{putExtra(MainActivity.EXTRA_ROUTE,route);flags=Intent.FLAG_ACTIVITY_SINGLE_TOP or Intent.FLAG_ACTIVITY_CLEAR_TOP},PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT)
    private fun serviceIntent(code:Int,action:String)=PendingIntent.getService(this,code,Intent(this,MonitoringService::class.java).apply{this.action=action},PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT)
    private fun startForegroundCompat(n:Notification){try{if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.UPSIDE_DOWN_CAKE)startForeground(NOTIFICATION_ID,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE)else startForeground(NOTIFICATION_ID,n)}catch(_:Throwable){stopSelf()}}
    private fun createChannels(){if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){notificationManager().createNotificationChannel(NotificationChannel(CHANNEL_ID,getString(R.string.monitoring_channel_name),NotificationManager.IMPORTANCE_LOW));notificationManager().createNotificationChannel(NotificationChannel(ALERT_CHANNEL_ID,getString(R.string.alert_channel_name),NotificationManager.IMPORTANCE_HIGH))}}
    private fun notificationManager()=getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    override fun onDestroy(){job?.cancel();scope.cancel();runCatching{stopForeground(true)};super.onDestroy()};override fun onBind(intent:Intent?):IBinder?=null
    companion object{const val CHANNEL_ID="monitored_check_monitoring";const val ALERT_CHANNEL_ID="monitored_check_alerts";const val NOTIFICATION_ID=1001;const val ALERT_ID=2000;const val ACTION_STOP="com.monitorcheck.action.STOP_MONITORING";const val ACTION_PAUSE="com.monitorcheck.action.PAUSE_MONITORING";const val ACTION_RESUME="com.monitorcheck.action.RESUME_MONITORING";const val ACTION_TOGGLE_ALERTS="com.monitorcheck.action.TOGGLE_ALERTS";fun start(c:Context){runCatching{if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O)c.startForegroundService(Intent(c,MonitoringService::class.java))else c.startService(Intent(c,MonitoringService::class.java))}};fun stop(c:Context){runCatching{c.stopService(Intent(c,MonitoringService::class.java))}}}
}
