package com.monitorcheck.logs

import android.content.Context
import android.os.Build
import com.monitorcheck.core.Reading
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.withContext
import java.io.BufferedReader
import java.io.File
import java.io.InputStreamReader

enum class LogPriority(val letter: String, val label: String, val rank: Int) {
    VERBOSE("V", "Verbose", 0),
    DEBUG("D", "Debug", 1),
    INFO("I", "Info", 2),
    WARN("W", "Warning", 3),
    ERROR("E", "Error", 4),
    FATAL("F", "Fatal", 5),
    UNKNOWN("?", "Unknown", 0);

    companion object {
        fun fromLetter(c: String) = entries.firstOrNull { it.letter == c } ?: UNKNOWN
    }
}

data class LogLine(
    val raw: String,
    val timestamp: String?,
    val pid: Int?,
    val tid: Int?,
    val priority: LogPriority,
    val tag: String?,
    val message: String
)

class LogcatRepository(private val context: Context) {

    private val threadtimeRegex = Regex(
        """^(\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}\.\d{3})\s+(\d+)\s+(\d+)\s+([VDIWEFS])\s+([^:]*?):\s?(.*)$"""
    )

    fun accessLevel(): Reading<String> {
        val hasReadLogs = context.checkSelfPermission("android.permission.READ_LOGS") ==
            android.content.pm.PackageManager.PERMISSION_GRANTED
        return when {
            hasReadLogs -> Reading.available(
                "System-wide log access granted (READ_LOGS held)",
                "PackageManager permission check")
            else -> Reading.limited(
                "Own-application logs only",
                "Android restricts READ_LOGS to system and privileged apps. Monitored Check can " +
                    "read only the log entries generated by its own UID. This is an Android " +
                    "security boundary and is not bypassed.",
                "Android platform policy"
            )
        }
    }

    suspend fun dump(maxLines: Int = 500): Reading<List<LogLine>> = withContext(Dispatchers.IO) {
        try {
            val cmd = listOf("logcat", "-d", "-v", "threadtime", "-t", maxLines.toString())
            val process = ProcessBuilder(cmd).redirectErrorStream(true).start()
            val lines = ArrayList<LogLine>()
            BufferedReader(InputStreamReader(process.inputStream)).use { reader ->
                var line = reader.readLine()
                while (line != null && lines.size < maxLines) {
                    parse(line)?.let { lines.add(it) }
                    line = reader.readLine()
                }
            }
            process.waitFor()
            when {
                lines.isEmpty() -> Reading.limited(
                    emptyList(),
                    "The log buffer returned no entries visible to this app. On Android 4.1+ an " +
                        "app can only see its own log output.",
                    "logcat -d"
                )
                else -> Reading.limited(lines,
                    "Showing entries visible to this app's UID only (Android security boundary)",
                    "logcat -d -v threadtime")
            }
        } catch (t: Throwable) {
            Reading.restricted(
                "The logcat binary could not be executed: ${t.javaClass.simpleName}. " +
                    "Some Android builds block process spawning for apps entirely."
            )
        }
    }

    fun stream(): Flow<LogLine> = callbackFlow {
        var process: Process? = null
        val thread = Thread {
            try {
                process = ProcessBuilder(listOf("logcat", "-v", "threadtime"))
                    .redirectErrorStream(true).start()
                BufferedReader(InputStreamReader(process!!.inputStream)).use { reader ->
                    var line = reader.readLine()
                    while (line != null && !isClosedForSend) {
                        parse(line)?.let { trySend(it) }
                        line = reader.readLine()
                    }
                }
            } catch (_: Throwable) {

            } finally {
                close()
            }
        }
        thread.isDaemon = true
        thread.start()
        awaitClose {
            runCatching { process?.destroy() }
            runCatching { thread.interrupt() }
        }
    }.flowOn(Dispatchers.IO)

    private fun parse(line: String): LogLine? {
        if (line.isBlank()) return null
        if (line.startsWith("---------")) return null
        val m = threadtimeRegex.find(line)
        return if (m != null) {
            val (ts, pid, tid, pri, tag, msg) = m.destructured
            LogLine(line, ts, pid.toIntOrNull(), tid.toIntOrNull(),
                LogPriority.fromLetter(pri), tag.trim(), msg)
        } else {
            LogLine(line, null, null, null, LogPriority.UNKNOWN, null, line)
        }
    }

    fun filter(
        lines: List<LogLine>,
        minPriority: LogPriority,
        query: String,
        tagFilter: String?
    ): List<LogLine> = lines.filter { l ->
        l.priority.rank >= minPriority.rank &&
            (tagFilter.isNullOrBlank() || l.tag?.contains(tagFilter, true) == true) &&
            (query.isBlank() || l.raw.contains(query, true))
    }

    suspend fun export(lines: List<LogLine>): Reading<File> = withContext(Dispatchers.IO) {
        try {
            val dir = File(context.filesDir, "logs").apply { mkdirs() }
            val file = File(dir, "logcat_${System.currentTimeMillis()}.txt")
            file.bufferedWriter().use { w ->
                w.write("Monitored Check — logcat export\n")
                w.write("Generated: ${com.monitorcheck.core.Fmt.timestamp(System.currentTimeMillis())}\n")
                w.write("Device: ${Build.MANUFACTURER} ${Build.MODEL} (Android ${Build.VERSION.RELEASE})\n")
                w.write("Scope: ${accessLevel().value ?: "unknown"}\n")
                w.write("Lines: ${lines.size}\n")
                w.write("${"=".repeat(70)}\n\n")
                lines.forEach { w.write(it.raw + "\n") }
            }
            Reading.available(file, "Local export")
        } catch (t: Throwable) {
            Reading.error(t.message)
        }
    }
}

private operator fun <T> List<T>.component6(): T = this[5]
